/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-legacy-car`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/car-detail`; params?: Router.UnknownInputParams; } | { pathname: `/dev-reset`; params?: Router.UnknownInputParams; } | { pathname: `/edit-legacy-car-photos`; params?: Router.UnknownInputParams; } | { pathname: `/edit-spot-photos`; params?: Router.UnknownInputParams; } | { pathname: `/edit-spot`; params?: Router.UnknownInputParams; } | { pathname: `/legacy-car-detail`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/manual-upload`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/post-spot`; params?: Router.UnknownInputParams; } | { pathname: `/profile-details`; params?: Router.UnknownInputParams; } | { pathname: `/rank-progression`; params?: Router.UnknownInputParams; } | { pathname: `/user-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-cars` | `/my-cars`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-legacy-car`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/car-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/dev-reset`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-legacy-car-photos`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-spot-photos`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-spot`; params?: Router.UnknownOutputParams; } | { pathname: `/legacy-car-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/manual-upload`; params?: Router.UnknownOutputParams; } | { pathname: `/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/post-spot`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-details`; params?: Router.UnknownOutputParams; } | { pathname: `/rank-progression`; params?: Router.UnknownOutputParams; } | { pathname: `/user-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-cars` | `/my-cars`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-legacy-car${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/car-detail${`?${string}` | `#${string}` | ''}` | `/dev-reset${`?${string}` | `#${string}` | ''}` | `/edit-legacy-car-photos${`?${string}` | `#${string}` | ''}` | `/edit-spot-photos${`?${string}` | `#${string}` | ''}` | `/edit-spot${`?${string}` | `#${string}` | ''}` | `/legacy-car-detail${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/manual-upload${`?${string}` | `#${string}` | ''}` | `/paywall${`?${string}` | `#${string}` | ''}` | `/post-spot${`?${string}` | `#${string}` | ''}` | `/profile-details${`?${string}` | `#${string}` | ''}` | `/rank-progression${`?${string}` | `#${string}` | ''}` | `/user-profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-cars${`?${string}` | `#${string}` | ''}` | `/my-cars${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/settings/edit-profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-legacy-car`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/car-detail`; params?: Router.UnknownInputParams; } | { pathname: `/dev-reset`; params?: Router.UnknownInputParams; } | { pathname: `/edit-legacy-car-photos`; params?: Router.UnknownInputParams; } | { pathname: `/edit-spot-photos`; params?: Router.UnknownInputParams; } | { pathname: `/edit-spot`; params?: Router.UnknownInputParams; } | { pathname: `/legacy-car-detail`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/manual-upload`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/post-spot`; params?: Router.UnknownInputParams; } | { pathname: `/profile-details`; params?: Router.UnknownInputParams; } | { pathname: `/rank-progression`; params?: Router.UnknownInputParams; } | { pathname: `/user-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-cars` | `/my-cars`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/settings/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
